### ISSUE TITLE
Error Starting Taskcafe

### ISSUE THREAD

**Issue by Fishy49** [JordanKnott/taskcafe#36]
When trying to run the following from the README:
```
docker-compose -p taskcafe -f docker-compose.yml -f docker-compose.migrate.yml run --rm migrate
```

I get this:
```
docker-compose -p taskcafe -f docker-compose.yml -f docker-compose.migrate.yml run --rm migrate
Starting taskcafe_postgres_1 ... done
panic: Config File "taskcafe" Not Found in "[/root/conf /root /etc/taskcafe]"

goroutine 1 [running]:
github.com/jordanknott/taskcafe/internal/commands.initConfig()
	/usr/src/app/internal/commands/commands.go:67 +0x30d
github.com/spf13/cobra.(*Command).preRun(0xc000135340)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:872 +0x49
github.com/spf13/cobra.(*Command).execute(0xc000135340, 0x138ab00, 0x0, 0x0, 0xc000135340, 0x138ab00)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:808 +0x138
github.com/spf13/cobra.(*Command).ExecuteC(0x1356a00, 0xc00016bf50, 0x3, 0x3)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/jordanknott/taskcafe/internal/commands.Execute()
	/usr/src/app/internal/commands/commands.go:74 +0xdc
main.main()
	/usr/src/app/cmd/taskcafe/main.go:9 +0x20
```

I tried copying the `conf/taskcafe.example.toml` to `conf/taskcafe.toml` and re-running the build but I still get the same error.

**Comment by JordanKnott** [comment]
Added a check in the latest commit that should fix this!
