### ISSUE TITLE
Using docker-compose fails - database connection refused

### ISSUE THREAD

**Issue by axeII** [JordanKnott/taskcafe#47]
Hi,

I am unable to run `taskcafe` using `docker-compse -f docker-compose.yml up` because connection seems to be blocked with database. Please see the log:

```
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  | 
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  | 
postgres_1  | Data page checksums are disabled.
postgres_1  | 
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1  | creating subdirectories ... ok
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
postgres_1  | selecting default time zone ... UTC
postgres_1  | creating configuration files ... ok
postgres_1  | running bootstrap script ... ok
web_1       | time="27-08-2020 13:24:59" level=panic msg="dial tcp 172.18.0.2:5432: connect: connection refused"
web_1       | panic: (*logrus.Entry) (0xbc4880,0xc0006104d0)
web_1       | 
web_1       | goroutine 1 [running]:
web_1       | github.com/sirupsen/logrus.Entry.log(0xc0000e1490, 0xc00061c9f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
web_1       | 	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x2da
web_1       | github.com/sirupsen/logrus.(*Entry).Log(0xc000610460, 0xc000000000, 0xc0000cfbc0, 0x1, 0x1)
web_1       | 	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xeb
web_1       | github.com/sirupsen/logrus.(*Logger).Log(0xc0000e1490, 0x0, 0xc0000cfbc0, 0x1, 0x1)
web_1       | 	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 +0x7d
web_1       | github.com/sirupsen/logrus.(*Logger).Panic(...)
web_1       | 	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:233
web_1       | github.com/sirupsen/logrus.Panic(...)
web_1       | 	/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/exported.go:129
web_1       | github.com/jordanknott/taskcafe/internal/commands.newWebCmd.func1(0xc0000aa580, 0x1665b20, 0x0, 0x0, 0x0, 0x0)
web_1       | 	/usr/src/app/internal/commands/web.go:41 +0x388
web_1       | github.com/spf13/cobra.(*Command).execute(0xc0000aa580, 0x1665b20, 0x0, 0x0, 0xc0000aa580, 0x1665b20)
web_1       | 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
web_1       | github.com/spf13/cobra.(*Command).ExecuteC(0x1631a20, 0xc0000cff50, 0x3, 0x3)
web_1       | 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
web_1       | github.com/spf13/cobra.(*Command).Execute(...)
web_1       | 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
web_1       | github.com/jordanknott/taskcafe/internal/commands.Execute()
web_1       | 	/usr/src/app/internal/commands/commands.go:71 +0xdc
web_1       | main.main()
web_1       | 	/usr/src/app/cmd/taskcafe/main.go:9 +0x20
postgres_1  | performing post-bootstrap initialization ... sh: locale: not found
postgres_1  | 2020-08-27 13:24:59.508 UTC [29] WARNING:  no usable system locales were found
postgres_1  | ok
postgres_1  | syncing data to disk ... ok
postgres_1  | initdb: warning: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
postgres_1  | 
postgres_1  | 
postgres_1  | Success. You can now start the database server using:
postgres_1  | 
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1  | 
postgres_1  | waiting for server to start....2020-08-27 13:25:01.113 UTC [34] LOG:  starting PostgreSQL 12.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
postgres_1  | 2020-08-27 13:25:01.116 UTC [34] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2020-08-27 13:25:01.140 UTC [35] LOG:  database system was shut down at 2020-08-27 13:25:00 UTC
postgres_1  | 2020-08-27 13:25:01.144 UTC [34] LOG:  database system is ready to accept connections
postgres_1  |  done
postgres_1  | server started
postgres_1  | CREATE DATABASE
postgres_1  | 
postgres_1  | 
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  | 
postgres_1  | 2020-08-27 13:25:01.457 UTC [34] LOG:  received fast shutdown request
postgres_1  | waiting for server to shut down....2020-08-27 13:25:01.460 UTC [34] LOG:  aborting any active transactions
postgres_1  | 2020-08-27 13:25:01.462 UTC [34] LOG:  background worker "logical replication launcher" (PID 41) exited with exit code 1
postgres_1  | 2020-08-27 13:25:01.462 UTC [36] LOG:  shutting down
postgres_1  | 2020-08-27 13:25:01.477 UTC [34] LOG:  database system is shut down
postgres_1  |  done
postgres_1  | server stopped
postgres_1  | 
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  | 
postgres_1  | 2020-08-27 13:25:01.570 UTC [1] LOG:  starting PostgreSQL 12.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
postgres_1  | 2020-08-27 13:25:01.570 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2020-08-27 13:25:01.571 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2020-08-27 13:25:01.575 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2020-08-27 13:25:01.592 UTC [45] LOG:  database system was shut down at 2020-08-27 13:25:01 UTC
postgres_1  | 2020-08-27 13:25:01.597 UTC [1] LOG:  database system is ready to accept connections
```

Any thoughts how to make it work?
Thanks.

**Comment by JordanKnott** [comment]
Sometimes the web service starts before the postgres docker image is ready to accept connections, so it fails. I'm looking into the best way to handle this (as I'm not sure how!) - for now, you should just be able to restart the web server image to get it to connect (`docker container restart taskcafe_web_1`)

**Comment by AlexPlom** [comment]
Since this is mostly a startup issue, a simple retry with sleeps, when the connection fails, should do the job. The postgresql issue is a general docker issue.

**Comment by JordanKnott** [comment]
Added retry with backoff to the database as of commit 4988176
