### ISSUE TITLE
A member user in a project can't move or edit a card

### ISSUE THREAD

**Issue by gandalfmagic** [JordanKnott/taskcafe#65]
**Describe the bug**
I've added a new user with member permissions to a project.
The user try to move or edit an existing card, but the service gives an error, and the action fails.

**Service log output**
```time="22-09-2020 13:19:00" level=info msg="getting field by name" fieldName=ProjectID typeArg=PROJECT
reflect: call of reflect.Value.Interface on zero Value

goroutine 11805 [running]:
runtime/debug.Stack(0x1, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/99designs/gqlgen/graphql.DefaultRecover(0x1b6e100, 0xc0007a4720, 0x1343b00, 0xc00000ebc0, 0x1411de0, 0x1533ae4)
	/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/graphql/recovery.go:16 +0xa7
github.com/jordanknott/taskcafe/internal/graph.(*executionContext)._Mutation_updateTaskLocation.func1(0xc00077a310, 0xc00077a350, 0xc000f7af20)
	/usr/src/app/internal/graph/generated.go:6722 +0x78
panic(0x1343b00, 0xc00000ebc0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
reflect.valueInterface(0x0, 0x0, 0x0, 0x1533a01, 0x9, 0x0)
	/usr/local/go/src/reflect/value.go:998 +0x1a5
reflect.Value.Interface(...)
	/usr/local/go/src/reflect/value.go:993
github.com/jordanknott/taskcafe/internal/graph.NewHandler.func1(0x1b6e100, 0xc0007a4720, 0x0, 0x0, 0xc00000eb60, 0xc00077a380, 0x1, 0x1, 0x15312b7, 0x7, ...)
	/usr/src/app/internal/graph/graph.go:58 +0x488
github.com/jordanknott/taskcafe/internal/graph.(*executionContext)._Mutation_updateTaskLocation.func2.2(0x1b6e100, 0xc0007a4720, 0x14343e0, 0x0, 0x0, 0x20)
	/usr/src/app/internal/graph/generated.go:6762 +0x266
github.com/jordanknott/taskcafe/internal/graph.(*executionContext)._Mutation_updateTaskLocation.func2(0x1b6e100, 0xc0007a4720, 0x20, 0x14343e0, 0xc0007a4701, 0xc00000eb40)
	/usr/src/app/internal/graph/generated.go:6765 +0xcf
github.com/99designs/gqlgen/graphql/executor.processExtensions.func3(0x1b6e100, 0xc0007a4720, 0xc00000eb40, 0xc0007a4750, 0xc0007a47b0, 0x0, 0x0)
	/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/graphql/executor/extensions.go:62 +0x3a
github.com/jordanknott/taskcafe/internal/graph.(*executionContext)._Mutation_updateTaskLocation(0xc00077a310, 0x1b6e100, 0xc0007a46f0, 0xc000877280, 0xc0007a46c0, 0x3, 0x3, 0x0, 0x0)
	/usr/src/app/internal/graph/generated.go:6741 +0x2af
github.com/jordanknott/taskcafe/internal/graph.(*executionContext)._Mutation(0xc00077a310, 0x1b6e100, 0xc0007a46f0, 0xc0008aa930, 0x1, 0x1, 0x40e416, 0xc0007a4690)
	/usr/src/app/internal/graph/generated.go:16728 +0x2bef
github.com/jordanknott/taskcafe/internal/graph.(*executableSchema).Exec.func2(0x1b6e100, 0xc0007a4690, 0x10)
	/usr/src/app/internal/graph/generated.go:2441 +0x7b
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1.1(0x1b6e100, 0xc0007a4690, 0xc00077a330)
	/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/graphql/executor/executor.go:105 +0x43
github.com/99designs/gqlgen/graphql/executor.processExtensions.func2(0x1b6e100, 0xc0007a4690, 0xc00077a330, 0x1b1f9e0)
	/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/graphql/executor/extensions.go:59 +0x3a
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1(0x1b6e100, 0xc0007a4630, 0xc0007a44e0)
	/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/graphql/executor/executor.go:104 +0x12a
github.com/99designs/gqlgen/graphql/handler/transport.POST.Do(0x7f9d429cdc68, 0xc0000dd400, 0xc00082c600, 0x1b653c0, 0xc00067f9e0)
	/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/graphql/handler/transport/http_post.go:52 +0x353
github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0xc0006fe5c0, 0x7f9d429cdc68, 0xc0000dd400, 0xc00082c600)
	/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/graphql/handler/server.go:115 +0x1fd
github.com/jordanknott/taskcafe/internal/route.(*AuthenticationMiddleware).Middleware.func1(0x7f9d429cdc68, 0xc0000dd400, 0xc00082c400)
	/usr/src/app/internal/route/middleware.go:65 +0x694
net/http.HandlerFunc.ServeHTTP(0xc0006fe660, 0x7f9d429cdc68, 0xc0000dd400, 0xc00082c400)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0xc0000ce380, 0x7f9d429cdc68, 0xc0000dd400, 0xc00082c400)
	/go/pkg/mod/github.com/go-chi/chi@v3.3.2+incompatible/chain.go:31 +0x52
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0005013e0, 0x7f9d429cdc68, 0xc0000dd400, 0xc00082c400)
	/go/pkg/mod/github.com/go-chi/chi@v3.3.2+incompatible/mux.go:424 +0x278
net/http.HandlerFunc.ServeHTTP(0xc000119610, 0x7f9d429cdc68, 0xc0000dd400, 0xc00082c400)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi/middleware.Timeout.func1.1(0x7f9d429cdc68, 0xc0000dd400, 0xc00082c300)
	/go/pkg/mod/github.com/go-chi/chi@v3.3.2+incompatible/middleware/timeout.go:44 +0x1ca
net/http.HandlerFunc.ServeHTTP(0xc0006fe260, 0x7f9d429cdc68, 0xc0000dd400, 0xc00082c300)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi/middleware.Recoverer.func1(0x7f9d429cdc68, 0xc0000dd400, 0xc00082c300)
	/go/pkg/mod/github.com/go-chi/chi@v3.3.2+incompatible/middleware/recoverer.go:35 +0x83
net/http.HandlerFunc.ServeHTTP(0xc0006fe280, 0x7f9d429cdc68, 0xc0000dd400, 0xc00082c300)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi/middleware.RequestLogger.func1.1(0x1b67600, 0xc000742000, 0xc00082c200)
	/go/pkg/mod/github.com/go-chi/chi@v3.3.2+incompatible/middleware/logger.go:46 +0x1d7
net/http.HandlerFunc.ServeHTTP(0xc0006fa840, 0x1b67600, 0xc000742000, 0xc00082c200)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi/middleware.RealIP.func1(0x1b67600, 0xc000742000, 0xc00082c200)
	/go/pkg/mod/github.com/go-chi/chi@v3.3.2+incompatible/middleware/realip.go:34 +0x99
net/http.HandlerFunc.ServeHTTP(0xc0006fe2a0, 0x1b67600, 0xc000742000, 0xc00082c200)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi/middleware.RequestID.func1(0x1b67600, 0xc000742000, 0xc00082c100)
	/go/pkg/mod/github.com/go-chi/chi@v3.3.2+incompatible/middleware/request_id.go:68 +0x287
net/http.HandlerFunc.ServeHTTP(0xc0006fe2c0, 0x1b67600, 0xc000742000, 0xc00082c100)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0005013e0, 0x1b67600, 0xc000742000, 0xc00082c000)
	/go/pkg/mod/github.com/go-chi/chi@v3.3.2+incompatible/mux.go:81 +0x2b2
net/http.serverHandler.ServeHTTP(0xc000724000, 0x1b67600, 0xc000742000, 0xc00082c000)
	/usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc000a88280, 0x1b6e040, 0xc0000d6780)
	/usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2962 +0x35c
```

**Comment by JordanKnott** [comment]
What version are you using? This should be fixed in the latest version.

**Comment by gandalfmagic** [comment]
I'm using a kuberneted deployment with `taskcafe/taskcafe:0.2.2` container

**Comment by JordanKnott** [comment]
Ah, if you use the `taskcafe/taskcafe:nightly` image, it is fixed (nightly is auto built on new commits).

**Comment by gandalfmagic** [comment]
Yes, fixed with the `nightly` version.

Thank you
